const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium}=require('playwright'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),executablePath=[process.env.GC_TEST_BROWSER_PATH,chromium.executablePath(),'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome','/usr/bin/chromium'].filter(Boolean).find(fs.existsSync);
const profile=require('./load-lib.cjs')('vision/attention-contracts').ATTENTION_PROFILE,manifest=JSON.parse(fs.readFileSync(path.join(root,'public/vision-lab/attention-v1-assets.json'),'utf8'));
const assetRoot=process.env.GC_TEST_VISION_ASSETS||'/tmp/gridcast-vision-spike/assets';
const available=manifest.assets.every(asset=>fs.existsSync(path.join(assetRoot,asset.name)));
const skip=!executablePath?'Chromium unavailable':!available?'Pinned real attention runtime assets are unavailable locally':false;
const compile=file=>ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
const bundle=`const c={exports:{}};new Function('require','module','exports',${JSON.stringify(compile('lib/vision/attention-contracts.ts'))})(()=>({}),c,c.exports);
const m={exports:{}};new Function('require','module','exports',${JSON.stringify(compile('lib/vision/metrics.ts'))})(()=>({}),m,m.exports);
const e={exports:{}};new Function('require','module','exports',${JSON.stringify(compile('lib/vision/engine.ts'))})(()=>({}),e,e.exports);
const p={exports:{}};new Function('require','module','exports',${JSON.stringify(compile('lib/vision/production.ts'))})(n=>n==='./attention-contracts'?c.exports:n==='./engine'?e.exports:n==='./metrics'?m.exports:{},p,p.exports);window.attention=p.exports;`;
const mime=name=>name.endsWith('.mjs')||name.endsWith('.js')?'application/javascript':name.endsWith('.json')?'application/json':'application/octet-stream';

test('production Attention V1 verifies cold files, uses its pinned worker despite stale lab cache, and restarts inference offline', {skip,timeout:180000},async t=>{
 const verified=new Map(manifest.assets.map(asset=>{const bytes=fs.readFileSync(path.join(assetRoot,asset.name));assert.equal(bytes.length,asset.bytes,asset.name+' byte count');assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),asset.sha256,asset.name+' SHA-256');return[asset.url,{...asset,bytes}];}));
 const webm=fs.readFileSync(path.join(root,'public/diagnostics/screen-test.mp4'));
 const app=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');
  if(u.pathname==='/player-sw.js'){res.setHeader('Content-Type','application/javascript');return res.end(fs.readFileSync(path.join(root,'public/player-sw.js')));}
  if(u.pathname===profile.worker_url){res.setHeader('Content-Type','application/javascript');return res.end(fs.readFileSync(path.join(root,'public'+profile.worker_url)));}
  if(u.pathname==='/vision-lab/attention-v1-assets.json'){res.setHeader('Content-Type','application/json');return res.end(fs.readFileSync(path.join(root,'public/vision-lab/attention-v1-assets.json')));}
  if(u.pathname==='/_next/static/attention-fixture.js'){res.setHeader('Content-Type','application/javascript');return res.end(bundle);}
  res.setHeader('Content-Type','text/html');res.end('<!doctype html><body>Current player shell v2</body><video id="video" muted playsinline></video><script src="/_next/static/attention-fixture.js"></script>');
 });
 await new Promise(resolve=>app.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+app.address().port;
 let browser;
 try{
  browser=await chromium.launch({executablePath,headless:true,args:['--enable-unsafe-swiftshader']});const context=await browser.newContext(),transfers=[];
  await context.route('**/*',async route=>{const url=route.request().url();if(url.startsWith(base+'/'))return route.continue();const asset=verified.get(url);if(!asset){transfers.push({url,blocked:true});return route.abort('blockedbyclient');}transfers.push({url,name:asset.name});return route.fulfill({status:200,headers:{'Content-Type':mime(asset.name),'Access-Control-Allow-Origin':'*'},body:asset.bytes});});
  const page=await context.newPage();page.setDefaultTimeout(60000);const errors=[],consoleErrors=[],failedRequests=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});page.on('requestfailed',request=>failedRequests.push({url:request.url(),failure:request.failure()?.errorText}));
  await page.goto(base+'/player');await page.evaluate(async()=>{await caches.open('gridcast-vision-lab-shell-1').then(async cache=>{await cache.put('/vision-lab/worker.js',new Response('stale worker without production context support'));await cache.put('/vision-lab/assets.json',new Response('{"version":"stale"}'));});await caches.open('gridcast-player-shell-v1').then(cache=>cache.put('/player',new Response('<!doctype html><body>Stale player shell v1</body>')));});
  const cold=await page.evaluate(async()=>{const progress=[],controller=new AbortController();const assets=await attention.prepareAttentionAssets(v=>progress.push(v),controller.signal);const samples=[];const worker=await attention.createProductionAttentionWorker(controller.signal,value=>samples.push(value),message=>{throw Error(message);});
    const canvas=document.createElement('canvas');canvas.width=320;canvas.height=240;canvas.getContext('2d').fillRect(0,0,320,240);const video=document.querySelector('video');video.srcObject=canvas.captureStream(15);await video.play();await new Promise(resolve=>video.readyState>=2?resolve():video.addEventListener('loadeddata',resolve,{once:true}));
    const observation=new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('No real model observation arrived')),45000);const poll=setInterval(()=>{if(samples.length){clearTimeout(timeout);clearInterval(poll);resolve(samples[0]);}},20);});await worker.frame(video,{yaw:0,pitch:0});const result=await observation;worker.close();video.srcObject.getTracks().forEach(track=>track.stop());controller.abort();return{assets,progress,last:progress.at(-1),observation:{bodies:result.bodies,faces:result.faces}};}).catch(error=>{throw Error(`${error.message}\ntransfers=${JSON.stringify(transfers)}\nconsole=${JSON.stringify(consoleErrors)}\npage=${JSON.stringify(errors)}`);});
  assert.equal(cold.assets.verified,cold.assets.bytes);assert.ok(cold.assets.downloaded>0,'Cold setup transferred model bytes');assert.equal(cold.last.verified,cold.assets.bytes);assert.ok(cold.progress.some(p=>p.phase==='downloading'));assert.deepEqual(cold.observation.bodies,{ok:true,boxes:[],saturated:false});assert.deepEqual(cold.observation.faces,{ok:true,faces:[],saturated:false});
  await page.evaluate(async()=>{await navigator.serviceWorker.register('/player-sw.js',{scope:'/player'});await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));navigator.serviceWorker.controller.postMessage({type:'PREPARE_PLAYER',urls:[location.origin+'/_next/static/attention-fixture.js']});await fetch('/_next/static/attention-fixture.js');});await page.waitForFunction(async()=>!!await caches.match('/_next/static/attention-fixture.js'));
  const preOffline=await page.evaluate(async()=>({worker:!!await (await caches.open('gridcast-player-shell-v2')).match('/vision-lab/worker-attention-v1.js'),manifest:!!await(await caches.open('gridcast-player-shell-v2')).match('/vision-lab/attention-v1-assets.json'),count:(await caches.open('gridcast-vision-lab-assets-1').then(c=>c.keys())).length}));assert.equal(preOffline.worker,true);assert.equal(preOffline.manifest,true);assert.equal(preOffline.count,7);
  await context.setOffline(true);await page.reload();await page.waitForFunction(()=>!!window.attention&&!!navigator.serviceWorker.controller);
  assert.match(await page.locator('body').innerText(),/Current player shell v2/,'Offline navigation must use the current dedicated player cache, not the seeded v1 cache');
  const warm=await page.evaluate(async()=>{const progress=[],controller=new AbortController(),assets=await attention.prepareAttentionAssets(v=>progress.push(v),controller.signal),observations=[];const worker=await attention.createProductionAttentionWorker(controller.signal,value=>observations.push(value),message=>{throw Error(message);});const canvas=document.createElement('canvas');canvas.width=320;canvas.height=240;canvas.getContext('2d').fillRect(0,0,320,240);const video=document.querySelector('video');video.srcObject=canvas.captureStream(15);await video.play();await new Promise(resolve=>video.readyState>=2?resolve():video.addEventListener('loadeddata',resolve,{once:true}));const observation=new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('No offline model observation arrived')),45000),poll=setInterval(()=>{if(observations.length){clearTimeout(timeout);clearInterval(poll);resolve(observations[0]);}},20);});await worker.frame(video,{yaw:0,pitch:0});const result=await observation;worker.close();video.srcObject.getTracks().forEach(track=>track.stop());controller.abort();return{assets,progress,observation:{bodies:result.bodies,faces:result.faces}};}).catch(error=>{throw Error(`${error.message}\nconsole=${JSON.stringify(consoleErrors)}\nrequests=${JSON.stringify(failedRequests)}\npage=${JSON.stringify(errors)}`);});
  assert.equal(warm.assets.downloaded,0,'Offline warm setup transfers no model bytes');assert.equal(warm.assets.verified,warm.assets.bytes);assert.equal(warm.progress.at(-1).verified,warm.assets.bytes);assert.ok(!warm.progress.some(p=>p.phase==='downloading'));assert.deepEqual(warm.observation.bodies,{ok:true,boxes:[],saturated:false});assert.deepEqual(warm.observation.faces,{ok:true,faces:[],saturated:false});
  const stale=await page.evaluate(async()=>({worker:await(await caches.open('gridcast-vision-lab-shell-1')).match('/vision-lab/worker.js')!==undefined,manifest:await(await caches.open('gridcast-vision-lab-shell-1')).match('/vision-lab/assets.json')!==undefined}));assert.deepEqual(stale,{worker:true,manifest:true});assert.deepEqual(errors,[]);
 }finally{await browser?.close();await new Promise(resolve=>app.close(resolve));}
});
