const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),ts=require('typescript');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const executablePath=[chromium.executablePath(),'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'].find(fs.existsSync);
const names=['lib/player-queue.ts','lib/player-diagnostics.ts','lib/player-evidence-lock.ts','lib/player-maintenance.ts','app/player/maintenance/page.tsx'];
const sources=Object.fromEntries(names.map(file=>[file,ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{fileName:file,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText]));
async function harness({current=false}={}){
 const grant={id:'grant1',org_id:'org1',screen_id:'screen1',device_id:'device1',expires_at:new Date(Date.now()+600000).toISOString()},requests=[];let pairFail=false,deny=false,holdExport=false,releaseExport;
 const bundle=`const sources=${JSON.stringify(sources)},modules={};function load(file){if(modules[file])return modules[file].exports;const m=modules[file]={exports:{}};const require=n=>{if(n==='react')return React;if(n==='@/components/ui/button')return {Button:({variant,...p})=>React.createElement('button',p)};if(n==='@/components/ui/input')return {Input:p=>React.createElement('input',p)};if(n==='@/components/ui/brand-mark')return {BrandLogo:()=>React.createElement('span',null,'Gridcast')};if(n.startsWith('@/lib/'))return load(n.slice(2)+'.ts');if(n.startsWith('./'))return load('lib/'+n.slice(2)+'.ts');throw Error(n);};new Function('require','module','exports',sources[file])(require,m,m.exports);return m.exports;}window.q=load('lib/player-queue.ts');window.d=load('lib/player-diagnostics.ts');ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(load('app/player/maintenance/page.tsx').default));`;
 const server=http.createServer(async(req,res)=>{
  if(req.url.startsWith('/api/')){let raw='';for await(const chunk of req)raw+=chunk;requests.push({path:req.url,body:JSON.parse(raw||'{}'),authorization:req.headers.authorization});res.setHeader('Content-Type','application/json');if(deny&&req.url!=='/api/maintenance/close'){res.statusCode=401;res.end('{"error":"Authorization withdrawn"}');return;}if(holdExport&&req.url==='/api/maintenance/export')await new Promise(resolve=>{releaseExport=resolve;});if(req.url==='/api/pair'){res.statusCode=pairFail?400:200;res.end(JSON.stringify(pairFail?{error:'Pairing code invalid'}:{token:'new-playback-token',device:{id:'device-new',screen_id:'screen-new'},screen:{id:'screen-new'}}));return;}if(req.url==='/api/play'){res.statusCode=503;res.end('{"error":"fixture delivery unavailable"}');return;}res.end(JSON.stringify({ok:true,grant,server_time:new Date().toISOString(),...(req.url.endsWith('/redeem')?{token:'fixture-maintenance-secret'}:{})}));return;}
  const files={'/react.js':'node_modules/react/umd/react.development.js','/react-dom.js':'node_modules/react-dom/umd/react-dom.development.js','/player-sw.js':'public/player-sw.js'};
  if(files[req.url]){res.setHeader('Content-Type','application/javascript');res.end(fs.readFileSync(path.join(root,files[req.url])));return;}
  if(req.url==='/bundle.js'){res.setHeader('Content-Type','application/javascript');res.end(bundle);return;}
  res.setHeader('Content-Type','text/html');res.end('<!doctype html><div id="root"></div><script src="/react.js"></script><script src="/react-dom.js"></script><script src="/bundle.js"></script>');
 });
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath}),context=await browser.newContext(),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/player/maintenance`);await page.getByLabel('Maintenance code',{exact:true}).waitFor();
 await page.evaluate(async current=>{await q.enqueuePlay('device1',{play_uid:'saved-one'});await q.enqueuePlay('foreign-device',{play_uid:'foreign-one'});await d.reserveDiagnostic('device1','diagnostic-1');await d.saveDiagnostic('device1',{run_uid:'diagnostic-1',measured:false,avg_persons:null});if(current)localStorage.setItem('gc_device',JSON.stringify({token:'old-playback-token',device_id:'device1',screen_id:'screen1'}));},current);
 const redeem=async()=>{await page.getByLabel('Maintenance code',{exact:true}).fill('ABCD-EFGH-JKLM-NPQR');await page.getByRole('button',{name:'Open maintenance',exact:true}).click();await page.getByText('1 pending deliveries · 0 blocked deliveries · 1 screen-test records',{exact:true}).waitFor();};
 return{page,context,requests,errors,redeem,setPairFail:v=>pairFail=v,setDenied:v=>deny=v,delayExport:()=>{holdExport=true;},releaseExport:()=>releaseExport?.(),cleanup:async()=>{await browser.close();await new Promise(r=>server.close(r));}};
}
const opts={skip:!executablePath};
test('maintenance UI downloads scoped evidence without deleting or persisting authority, and closes cleanly',opts,async()=>{
 const h=await harness();try{await h.redeem();assert.equal(await h.page.getByRole('button',{name:'Prepare replacement',exact:true}).count(),0);const download=h.page.waitForEvent('download');await h.page.getByRole('button',{name:'Export this identity’s records',exact:true}).click();const file=await download;const data=JSON.parse(fs.readFileSync(await file.path(),'utf8'));assert.equal(data.scope.device_id,'device1');assert.deepEqual(data.commercial.map(r=>r.event.play_uid),['saved-one']);assert.equal(data.diagnostics.reports.length,1);await h.page.getByText(/Download requested/).waitFor();assert.equal(await h.page.evaluate(async()=>JSON.stringify({...localStorage,...sessionStorage}).includes('fixture-maintenance-secret')),false);assert.equal(await h.page.evaluate(async()=>(await q.queuedPlays()).length),2);await h.page.getByRole('button',{name:'Close maintenance',exact:true}).click();await h.page.getByRole('button',{name:'Open maintenance',exact:true}).waitFor();assert.deepEqual(h.errors,[]);}finally{await h.cleanup();}
});
test('offline and reload close maintenance tools without clearing saved records',opts,async()=>{
 const h=await harness();try{await h.redeem();await h.page.evaluate(()=>window.dispatchEvent(new Event('offline')));await h.page.getByRole('button',{name:'Open maintenance',exact:true}).waitFor();assert.equal(await h.page.getByRole('button',{name:'Export this identity’s records',exact:true}).count(),0);assert.equal(await h.page.evaluate(async()=>(await q.queuedPlays()).length),2);await h.page.reload();await h.page.getByRole('button',{name:'Open maintenance',exact:true}).waitFor();assert.deepEqual(h.errors,[]);}finally{await h.cleanup();}
});
test('planned replacement requires export acknowledgement, preserves failed pairing and retains old evidence after success',opts,async()=>{
 const h=await harness({current:true});try{await h.redeem();await h.page.getByRole('button',{name:'Prepare replacement',exact:true}).click();await h.page.getByLabel('Destination pairing code').waitFor();const confirm=h.page.getByRole('button',{name:'Confirm replacement and keep records',exact:true});await h.page.getByLabel('Destination pairing code').fill('ABCDEFGH');assert.equal(await confirm.isDisabled(),true);const download=h.page.waitForEvent('download');await h.page.getByRole('button',{name:'Export this identity’s records',exact:true}).click();await download;await h.page.getByRole('checkbox').check();h.setPairFail(true);await confirm.click();await h.page.getByText('Pairing code invalid',{exact:true}).waitFor();assert.equal(await h.page.evaluate(()=>JSON.parse(localStorage.getItem('gc_device')).device_id),'device1');h.setPairFail(false);await confirm.click();await h.page.getByText(/Pairing replaced/).waitFor();assert.equal(await h.page.evaluate(()=>JSON.parse(localStorage.getItem('gc_device')).device_id),'device-new');assert.equal(await h.page.evaluate(async()=>(await q.queuedPlays('device1')).length),1);assert.equal(h.requests.filter(r=>r.path==='/api/pair').length,2);assert.deepEqual(h.errors,[]);}finally{await h.cleanup();}
});


test('authorization loss on refresh closes tools and leaves retained evidence',opts,async()=>{
 const h=await harness();try{await h.redeem();h.setDenied(true);await h.page.getByRole('button',{name:'Refresh saved records',exact:true}).click();await h.page.getByRole('button',{name:'Open maintenance',exact:true}).waitFor();await h.page.getByText('Authorization withdrawn',{exact:true}).waitFor();assert.equal(await h.page.evaluate(async()=>(await q.queuedPlays()).length),2);assert.deepEqual(h.errors,[]);}finally{await h.cleanup();}
});
test('hiding maintenance while export authorization is in flight prevents a late download',opts,async()=>{
 const h=await harness();try{await h.redeem();h.delayExport();let downloads=0;h.page.on('download',()=>downloads++);await h.page.getByRole('button',{name:'Export this identity’s records',exact:true}).click();const until=Date.now()+10000;while(!h.requests.some(r=>r.path==='/api/maintenance/export')){if(Date.now()>until)throw Error('export request missing');await new Promise(r=>setTimeout(r,20));}await h.page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});h.releaseExport();await h.page.getByRole('button',{name:'Open maintenance',exact:true}).waitFor();await new Promise(r=>setTimeout(r,300));assert.equal(downloads,0);assert.equal(await h.page.evaluate(async()=>(await q.queuedPlays()).length),2);assert.deepEqual(h.errors,[]);}finally{h.releaseExport();await h.cleanup();}
});
