'use client';
import React,{useState} from 'react';
import {token} from '@/lib/client';
import {cn} from '@/lib/utils';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';

/** Optional props let editors replace a source in place while library actions can add a clearly labelled variation. */
export function CreativeUpload({creativeId,mediaType='video',onUploaded,defaultOpen=false,onClose,onError,onBusyChange,onFileSelected,className,hideUploadError=false,replaceMode='append',imageDuration,operationLabel,metadata,disabled=false}:{creativeId:string;mediaType?:'image'|'video';onUploaded:(result:any)=>void;defaultOpen?:boolean;onClose?:()=>void;onError?:(message:string)=>void;onBusyChange?:(busy:boolean)=>void;onFileSelected?:(selected:boolean)=>void;className?:string;hideUploadError?:boolean;replaceMode?:'append'|'replace_all';imageDuration?:number;operationLabel?:string;metadata?:{name?:string;category?:string};disabled?:boolean}) {
  const [open,setOpen]=useState(defaultOpen),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[verified,setVerified]=useState<any>(null),[uploadFailed,setUploadFailed]=useState(false);
  const isImage=mediaType==='image', label=isImage?'image':'video', action=operationLabel??(replaceMode==='replace_all'?'Replace active media':'Add variation');
  const choose=(f:File|null)=>{setError('');setUploadFailed(false);setVerified(null);if(f&&(!(isImage?/\.(png|jpe?g|webp)$/i:/\.(mp4|webm)$/i).test(f.name)||f.size>(isImage?10:25)*1024*1024||f.size===0)){setFile(null);onFileSelected?.(false);setError(isImage?'Choose a static PNG, JPEG or WebP image up to 10 MB.':'Choose a non-empty MP4 or WebM video up to 25 MB.');return;}setFile(f);onFileSelected?.(!!f);};
  const upload=async()=>{if(!file||disabled)return;setBusy(true);onBusyChange?.(true);setError('');setUploadFailed(false);try{const credential=token.get();if(!credential)throw new Error('Sign in before uploading.');const form=new FormData();form.append('file',file);form.append('creative_id',creativeId);form.append('replace_mode',replaceMode);if(isImage&&typeof imageDuration==='number')form.append('image_duration_s',String(imageDuration));if(metadata?.name!==undefined)form.append('name',metadata.name);if(metadata?.category!==undefined)form.append('category',metadata.category);const response=await fetch('/api/assets/upload',{method:'POST',headers:{Authorization:`Bearer ${credential}`},body:form});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'The upload could not be completed.');setVerified(result.asset);setFile(null);onFileSelected?.(false);onUploaded(result);}catch(e){setError((e as Error).message);setUploadFailed(true);onError?.((e as Error).message);}finally{setBusy(false);onBusyChange?.(false);}};
  if(!open)return <Button size="sm" variant="outline" onClick={()=>setOpen(true)}>Upload {label}</Button>;
  return <div className={cn("min-w-[230px] max-w-md space-y-2 rounded-md border border-border p-3 text-sm",className)}>
    <Input type="file" accept={isImage?"image/png,image/jpeg,image/webp,.png,.jpg,.jpeg,.webp":"video/mp4,video/webm,.mp4,.webm"} aria-label={isImage?"PNG, JPEG or WebP image":"MP4 or WebM video"} disabled={busy||disabled} onChange={e=>choose(e.target.files?.[0]??null)}/>
    <p className="text-xs text-muted-foreground">{isImage?"Static PNG, JPEG or WebP, up to 10 MB. Animated images are not supported. Display time is set on the creative.":"MP4 or WebM, up to 25 MB. Duration comes from the video file."} Files stay on this computer until uploaded. {replaceMode==='replace_all'?'Current media stays active until the server verifies this file; then it is replaced.':'This adds a media variation and keeps the existing versions.'} A changed creative needs approval before it can play.</p>
    {file&&<p className="break-all text-xs">{file.name} · {(file.size/1024/1024).toFixed(1)} MB · metadata not yet verified</p>}
    {verified&&<p className="text-xs text-primary" role="status">Upload checked: {typeof verified.duration_s==='number'?`${verified.duration_s.toFixed(2)} seconds`:typeof verified.duration_ms==='number'?`${(verified.duration_ms/1000).toFixed(2)} seconds`:isImage?'still image verified':'metadata received'}{verified.width&&verified.height?` · ${verified.width} × ${verified.height}`:''}. Awaiting platform approval.</p>}
    {error&&!(hideUploadError&&uploadFailed)&&<p role="alert" className="text-xs text-destructive">{error}</p>}
    <div className="flex gap-2"><Button size="sm" disabled={!file||busy||disabled} onClick={upload}>{busy?'Uploading and checking…':action}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>{setOpen(false);setFile(null);setError('');onFileSelected?.(false);onClose?.();}}>Close</Button>{file&&!busy&&<Button size="sm" variant="ghost" disabled={disabled} onClick={()=>{setFile(null);setError('');setUploadFailed(false);onFileSelected?.(false);}}>Clear selection</Button>}</div>
  </div>;
}
